import os
from dotenv import load_dotenv

load_dotenv()

MODE = "demo"  

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

LLM_MODEL = "gpt-4o-mini"
EMBEDDING_MODEL = "text-embedding-3-small"

EMBEDDING_PRICE_PER_1M_TOKENS = 0.02
LLM_INPUT_PRICE_PER_1M_TOKENS = 0.15
LLM_OUTPUT_PRICE_PER_1M_TOKENS = 0.60

MAX_INPUT_CHARS = 1200
RATE_LIMIT_MAX_REQUESTS = 10
RATE_LIMIT_WINDOW_SECONDS = 3600

COLLECTION_NAME = "codebase"
VECTOR_SIZE = 1536
TOP_K = 7

HYBRID_DEBUG_LOGS = True
HYBRID_DEBUG_TOP_N = 5

CHUNK_SIZE = 500
CHUNK_OVERLAP = 100

MAX_INGEST_FILES = 25